package me.fusiondev.fusionpixelmon.api.config;

import info.pixelmon.repack.ninja.leaping.configurate.commented.CommentedConfigurationNode;
import info.pixelmon.repack.ninja.leaping.configurate.hocon.HoconConfigurationLoader;

import java.io.IOException;
import java.net.URL;
import java.nio.file.Path;

public abstract class ConfigManager extends AbstractConfigManager<CommentedConfigurationNode, HoconConfigurationLoader> {

    public ConfigManager(Path path) throws IOException {
        super(path, true);
    }

    protected HoconConfigurationLoader getLoader(Path path) {
        return HoconConfigurationLoader.builder().setPath(path).build();
    }

    protected CommentedConfigurationNode getDefaultsFrom(HoconConfigurationLoader loader) throws IOException {
        return HoconConfigurationLoader.builder().setURL(getUrl()).build().load(loader.getDefaultOptions());
    }

    @Override
    protected void configUpdater(int newVersion) throws IOException {
        // Backwards compatibility to remove 1.8 "currency" field
        getNode().getNode("pokedesigner").removeChild("currency");
        // Backwards compatibility to remove 1.8 "shrine-pickup" section
        getNode().removeChild("shrine-pickup");
        // Backwards compatibility to remove 1.8 "arcplate" field
        getNode().removeChild("arcplate");

        // Do you need also translate move's name & Pokemon's name & etc...
        getNode().getNode("Translation","Translation").setComment("If true, then you will only saw Traditional Chinese Translations at *PokemonName* , *MoveName* , etc...");
        getNode().getNode("Translation","Translation").setValue(false);

        getNode().getNode("Ability","AbilityInfoString1").setValue("To pick an ability for your Pokemon");
        getNode().getNode("Ability","AbilityInfoString2").setValue("simply select one of the possible options on the right.");
        getNode().getNode("Ability","AbilityInfoTitle").setValue("Ability Info");
        getNode().getNode("Ability","AbilityNormalSummary").setValue("Regular Ability");
        getNode().getNode("Ability","AbilityREGULAR").setValue("regular");
        getNode().getNode("Ability","AbilitySelectedTitle").setValue("Selected Ability");
        getNode().getNode("Ability","AbilitySPECIAL").setValue("special");
        getNode().getNode("Ability","AbilitySpecialSummary").setValue("Special Ability");
        getNode().getNode("Ability","AbilityTitle").setValue("Ability Modification");
        getNode().getNode("ArcPlates","ArcPlatesNotArc").setValue("Arc Plates");
        getNode().getNode("ArcPlates","ArcPlatesPlateCallArc").setValue("Your Arceus must be sent out before enabling hovering");
        getNode().getNode("ArcPlates","ArcPlatesPlateInfo1").setValue("In Storage:");
        getNode().getNode("ArcPlates","ArcPlatesPlateInfo1L").setValue("  Left Click: §aEquip Plate");
        getNode().getNode("ArcPlates","ArcPlatesPlateInfo1R").setValue("  Right Click: §aRemove Plate from Storage");
        getNode().getNode("ArcPlates","ArcPlatesPlateInfo2").setValue("In Inventory:");
        getNode().getNode("ArcPlates","ArcPlatesPlateMove").setValue("ArcPlates Hovering");
        getNode().getNode("ArcPlates","ArcPlatesPlateMoveInfo").setValue("Hover the plates around your Arceus");
        getNode().getNode("ArcPlates","ArcPlatesPlates").setValue(" Plate");
        getNode().getNode("ArcPlates","ArcPlatesPlateSave").setValue("Storage Info");
        getNode().getNode("ArcPlates","ArcPlatesPlatInfo2L").setValue("  Left Click: §aAdd Plate to Storage");
        getNode().getNode("Evolution","EvolutionCHANGE").setValue("change");
        getNode().getNode("Evolution","EvolutionInfoNote1").setValue("Note: can only get evolutions obtained by levelling.");
        getNode().getNode("Evolution","EvolutionInfoNote2").setValue("Evolving down may not permit to evolve back up.");
        getNode().getNode("Evolution","EvolutionInfoString1").setValue("To modify the evolution of your Pokemon");
        getNode().getNode("Evolution","EvolutionInfoTitle").setValue("Evolution Info");
        getNode().getNode("Evolution","EvolutionNameS").setValue("Unknown");
        getNode().getNode("Evolution","EvolutionPriceSummary").setValue("Change Evolution");
        getNode().getNode("Evolution","EvolutionSelectedTitle").setValue("Selected Evolution");
        getNode().getNode("Evolution","EvolutionTitle").setValue("Evolution Modification");
        getNode().getNode("Form","FormCHANGE").setValue("change");
        getNode().getNode("Form","FormInfoNote1").setValue("Note: Pokemon can revert/change form from held item change.");
        getNode().getNode("Form","FormInfoString1").setValue("To select a form for your Pokemon");
        getNode().getNode("Form","FormInfoString2").setValue("select one of the above options.");
        getNode().getNode("Form","FormInfoTitle").setValue("Form Info");
        getNode().getNode("Form","FormPriceSummery").setValue("Form Change");
        getNode().getNode("Form","FormSelectedTitle").setValue("Selected Form");
        getNode().getNode("Form","FormShiny").setValue("Shiny");
        getNode().getNode("Form","FormTitle").setValue("Form Modification");
        getNode().getNode("Gender","GenderCHANGE").setValue("change");
        getNode().getNode("Gender","GenderInfoString1").setValue("To pick a gender for your Pokemon");
        getNode().getNode("Gender","GenderInfoString2").setValue("simply select one of the options on the right.");
        getNode().getNode("Gender","GenderInfoTitle").setValue("Gender Info");
        getNode().getNode("Gender","GenderInvFemale").setValue("Female");
        getNode().getNode("Gender","GenderInvMale").setValue("Male");
        getNode().getNode("Gender","GenderNoSex").setValue("None");
        getNode().getNode("Gender","GenderPriceSummary").setValue("Gender Change");
        getNode().getNode("Gender","GenderSelectedFemale").setValue("Female");
        getNode().getNode("Gender","GenderSelectedMale").setValue("Male");
        getNode().getNode("Gender","GenderSelectedTitle").setValue("Selected Gender");
        getNode().getNode("Gender","GenderSetFemale").setValue("Click here to select the §dFemale §7gender.");
        getNode().getNode("Gender","GenderSetMale").setValue("Click here to select the §bMale §7gender.");
        getNode().getNode("Gender","GenderTitle").setValue("Gender Modification");
        getNode().getNode("Growth","GrowthEnormous").setValue("Enormous");
        getNode().getNode("Growth","GrowthGiant").setValue("Giant");
        getNode().getNode("Growth","GrowthGinormous").setValue("Ginormous");
        getNode().getNode("Growth","GrowthGrowth1").setValue("Normal Growth");
        getNode().getNode("Growth","GrowthGrowth2").setValue("Microscopic Growth");
        getNode().getNode("Growth","GrowthGrowth3").setValue("Ginormous Growth");
        getNode().getNode("Growth","GrowthHuge").setValue("Huge");
        getNode().getNode("Growth","GrowthInfoString1").setValue("To pick a growth for your Pokemon");
        getNode().getNode("Growth","GrowthInfoString2").setValue("simply select one of the options on the right.");
        getNode().getNode("Growth","GrowthInfoTitle").setValue("Growth");
        getNode().getNode("Growth","GrowthMicroscopic").setValue("Microscopic");
        getNode().getNode("Growth","GrowthOrdinary").setValue("Ordinary");
        getNode().getNode("Growth","GrowthPygmy").setValue("Pygmy");
        getNode().getNode("Growth","GrowthREGULAR").setValue("regular");
        getNode().getNode("Growth","GrowthRunt").setValue("Runt");
        getNode().getNode("Growth","GrowthSelectedTitle").setValue("Selected Growth");
        getNode().getNode("Growth","GrowthSmall").setValue("Small");
        getNode().getNode("Growth","GrowthSPECIAL").setValue("special");
        getNode().getNode("Growth","GrowthTitle").setValue("Growth Modification");
        getNode().getNode("IVEV","IVEVATK").setValue("ATK");
        getNode().getNode("IVEV","IVEVCurrent").setValue("Current:");
        getNode().getNode("IVEV","IVEVCurrentTotal").setValue("Current Total:");
        getNode().getNode("IVEV","IVEVDecrease").setValue("Decrease");
        getNode().getNode("IVEV","IVEVDEF").setValue("DEF");
        getNode().getNode("IVEV","IVEVEach").setValue("per");
        getNode().getNode("IVEV","IVEVHP").setValue("HP");
        getNode().getNode("IVEV","IVEVIncrease").setValue("Increase");
        getNode().getNode("IVEV","IVEVInfoString1").setValue("To modify the IVs/EVs for your Pokemon");
        getNode().getNode("IVEV","IVEVInfoString2").setValue("simply use the options.");
        getNode().getNode("IVEV","IVEVInfoTitle").setValue("IV/EV Info");
        getNode().getNode("IVEV","IVEVLeftClick").setValue("Left Click:");
        getNode().getNode("IVEV","IVEVLeftClickShift").setValue("Left Click + Shift:");
        getNode().getNode("IVEV","IVEVNotes").setValue("Note:");
        getNode().getNode("IVEV","IVEVRequested").setValue("Requested:");
        getNode().getNode("IVEV","IVEVRequestedTotal").setValue("Requested Total:");
        getNode().getNode("IVEV","IVEVSATK").setValue("SA");
        getNode().getNode("IVEV","IVEVSDEF").setValue("SD");
        getNode().getNode("IVEV","IVEVSPD").setValue("SPD");
        getNode().getNode("IVEV","IVEVTitle").setValue("IV/EV Modification");
        getNode().getNode("Level","LevelDecreaseLvl").setValue("Remove Level");
        getNode().getNode("Level","LevelEach").setValue("per level");
        getNode().getNode("Level","LevelIncreaseLvl").setValue("Add Level");
        getNode().getNode("Level","LevelInfoString1").setValue("To modify the levels for your Pokemon");
        getNode().getNode("Level","LevelInfoString2").setValue("simply use the above options.");
        getNode().getNode("Level","LevelInfoTitle").setValue("Level Info");
        getNode().getNode("Level","LevelLeftClick").setValue("Left Click:");
        getNode().getNode("Level","LevelLeftClickShift").setValue("Left Click + Shift:");
        getNode().getNode("Level","LevelNotes").setValue("Note:");
        getNode().getNode("Level","LevelPressDecrease").setValue("Click here to decrease the");
        getNode().getNode("Level","LevelPressIncrease").setValue("Click here to increase the level of your pokemon.");
        getNode().getNode("Level","LevelSelectedTitle").setValue("Selected Levels");
        getNode().getNode("Level","LevelTitle").setValue("Level Modification");
        getNode().getNode("Level","LevelZName").setValue("Lvl");
        getNode().getNode("Move","MoveCancel").setValue("Cancel");
        getNode().getNode("Move","MoveCHANGE").setValue("change-move");
        getNode().getNode("Move","MoveEach").setValue("per move");
        getNode().getNode("Move","MoveInfoString1").setValue("To pick a move for your Pokemon simply");
        getNode().getNode("Move","MoveInfoString2").setValue("click the move you wish to replace and");
        getNode().getNode("Move","MoveInfoString3").setValue("then choose the move you wish to learn instead.");
        getNode().getNode("Move","MoveInfoTitle").setValue("Move Info");
        getNode().getNode("Move","MoveLearning").setValue("Learning");
        getNode().getNode("Move","MoveLetStudy").setValue("Teach your Pokemon this move");
        getNode().getNode("Move","MoveMoveS").setValue("None");
        getNode().getNode("Move","MoveNextPage").setValue("Next");
        getNode().getNode("Move","MovePreviousPage").setValue("Back");
        getNode().getNode("Move","MovePriceSummary").setValue("Change Move");
        getNode().getNode("Move","MoveReplace").setValue("Replace");
        getNode().getNode("Move","MoveSelectedTitle").setValue("Selected Move");
        getNode().getNode("Move","MoveTitle").setValue("Move Modification");
        getNode().getNode("Nature","NatureATK").setValue("Attack");
        getNode().getNode("Nature","NatureCHANGE").setValue("change");
        getNode().getNode("Nature","NatureDecreased").setValue("Lowered:");
        getNode().getNode("Nature","NatureDEF").setValue("Defence");
        getNode().getNode("Nature","NatureHP").setValue("HP");
        getNode().getNode("Nature","NatureIncreased").setValue("Boosted:");
        getNode().getNode("Nature","NatureInfoString1").setValue("To pick a nature for your Pokemon");
        getNode().getNode("Nature","NatureInfoString2").setValue("simply select one of the options on the right.");
        getNode().getNode("Nature","NatureInfoTitle").setValue("Nature Info");
        getNode().getNode("Nature","NaturePriceSummary").setValue("Nature Change");
        getNode().getNode("Nature","NatureSATK").setValue("Special Attack");
        getNode().getNode("Nature","NatureSDEF").setValue("Special Defence");
        getNode().getNode("Nature","NatureSelectedTitle").setValue("Selected Nature");
        getNode().getNode("Nature","NatureSPD").setValue("Speed");
        getNode().getNode("Nature","NatureTitle").setValue("Nature Modification");
        getNode().getNode("Nick","NickAqua").setValue("Aqua");
        getNode().getNode("Nick","NickBlack").setValue("Black");
        getNode().getNode("Nick","NickBlue").setValue("Blue");
        getNode().getNode("Nick","NickBold").setValue("Bold");
        getNode().getNode("Nick","NickcolorPriceSummary").setValue("change-colour");
        getNode().getNode("Nick","NickDarkAqua").setValue("Dark Aqua");
        getNode().getNode("Nick","NickDarkBlue").setValue("Dark Blue");
        getNode().getNode("Nick","NickDarkGray").setValue("Dark Gray");
        getNode().getNode("Nick","NickDarkGreen").setValue("Dark Green");
        getNode().getNode("Nick","NickDarkPurple").setValue("Dark Purple");
        getNode().getNode("Nick","NickDarkRed").setValue("Dark red");
        getNode().getNode("Nick","NickGold").setValue("Gold");
        getNode().getNode("Nick","NickGray").setValue("Gray");
        getNode().getNode("Nick","NickGreen").setValue("Green");
        getNode().getNode("Nick","NickInfoString1").setValue("To pick a nick colour or style for your");
        getNode().getNode("Nick","NickInfoString2").setValue("Pokemon simply use the options above.");
        getNode().getNode("Nick","NickInfoString3").setValue("Colours and styles can be bought at once.");
        getNode().getNode("Nick","NickInfoTitle").setValue("Nick Info");
        getNode().getNode("Nick","NickItalic").setValue("Italic");
        getNode().getNode("Nick","NickLightPurple").setValue("Light Purple");
        getNode().getNode("Nick","NickObfuscated").setValue("Obfuscated");
        getNode().getNode("Nick","NickPurple").setValue("Purple");
        getNode().getNode("Nick","NickRed").setValue("Red red");
        getNode().getNode("Nick","NickReset").setValue("Reset");
        getNode().getNode("Nick","NickSelectedTitle").setValue("Selected Nick Colour");
        getNode().getNode("Nick","NickStrikethrough").setValue("Strikethrough");
        getNode().getNode("Nick","NickthemePriceSummary").setValue("change-style");
        getNode().getNode("Nick","NickTitle").setValue("Nick Modification");
        getNode().getNode("Nick","NickUnderline").setValue("Underline");
        getNode().getNode("Nick","NickWhite").setValue("White");
        getNode().getNode("Nick","NickYellow").setValue("Yellow");
        getNode().getNode("PokeBall","PokeBallBEAST").setValue("beast");
        getNode().getNode("PokeBall","PokeBallBeastBall").setValue("Beast Ball");
        getNode().getNode("PokeBall","PokeBallCherishBall").setValue("Cherish Ball");
        getNode().getNode("PokeBall","PokeBallDiveBall").setValue("Dive Ball");
        getNode().getNode("PokeBall","PokeBallDreamBall").setValue("Dream Ball");
        getNode().getNode("PokeBall","PokeBallDuskBall").setValue("Dusk Ball");
        getNode().getNode("PokeBall","PokeBallFastBall").setValue("Fast Ball");
        getNode().getNode("PokeBall","PokeBallFriendBall").setValue("Friend Ball");
        getNode().getNode("PokeBall","PokeBallGOD").setValue("god");
        getNode().getNode("PokeBall","PokeBallGreatBall").setValue("Great Ball");
        getNode().getNode("PokeBall","PokeBallGSBall").setValue("GS Ball");
        getNode().getNode("PokeBall","PokeBallHealBall").setValue("Heal Ball");
        getNode().getNode("PokeBall","PokeBallHeavyBall").setValue("Heavy Ball");
        getNode().getNode("PokeBall","PokeBallInfoString1").setValue("To pick the Pokeball for your Pokemon");
        getNode().getNode("PokeBall","PokeBallInfoString2").setValue("simply use the options above.");
        getNode().getNode("PokeBall","PokeBallInfoTitle").setValue("Pokeball Info");
        getNode().getNode("PokeBall","PokeBallLevelBall").setValue("Level Ball");
        getNode().getNode("PokeBall","PokeBallLoveBall").setValue("Love Ball");
        getNode().getNode("PokeBall","PokeBallLureBall").setValue("Lure Ball");
        getNode().getNode("PokeBall","PokeBallLuxuryBall").setValue("Luxury Ball");
        getNode().getNode("PokeBall","PokeBallMasterBall").setValue("Master Ball");
        getNode().getNode("PokeBall","PokeBallNormal").setValue("Normal Poke Ball");

        getNode().getNode("PokeBall","PokeBallNestBall").setValue("Nest Ball");
        getNode().getNode("PokeBall","PokeBallNetBall").setValue("Net Ball");
        getNode().getNode("PokeBall","PokeBallParkBall").setValue("Park Ball");
        getNode().getNode("PokeBall","PokeBallPokeBall").setValue("Poke Ball");
        getNode().getNode("PokeBall","PokeBallPremierBall").setValue("Premier Ball");
        getNode().getNode("PokeBall","PokeBallQuickBall").setValue("Quick Ball");
        getNode().getNode("PokeBall","PokeBallREGULAR").setValue("regular");
        getNode().getNode("PokeBall","PokeBallRepeatBall").setValue("Repeat Ball");
        getNode().getNode("PokeBall","PokeBallSafariBall").setValue("Safari Ball");
        getNode().getNode("PokeBall","PokeBallSelectedTitle").setValue("Selected Pokeball");
        getNode().getNode("PokeBall","PokeBallSPECIAL").setValue("special");
        getNode().getNode("PokeBall","PokeBallSportBall").setValue("Sport Ball");
        getNode().getNode("PokeBall","PokeBallTimerBall").setValue("Timer Ball");
        getNode().getNode("PokeBall","PokeBallTitle").setValue("okeball Modification");
        getNode().getNode("PokeBall","PokeBallUltraBall").setValue("Ultra Ball");
        getNode().getNode("Shiny","ShinyShinyInfoString1").setValue("To select the shininess of");
        getNode().getNode("Shiny","ShinyShinyInfoString2").setValue("your Pokemon simply select one of the options on the right.");
        getNode().getNode("Shiny","ShinyShinyInfoTitle").setValue("Shiny Info");
        getNode().getNode("Shiny","ShinyShinyaDPriceSummary").setValue("Remove Shininess");
        getNode().getNode("Shiny","ShinyShinyChoose").setValue("add");
        getNode().getNode("Shiny","ShinyShinyDelete").setValue("remove");
        getNode().getNode("Shiny","ShinyShinySelectedTitle").setValue("Selected Shininess");
        getNode().getNode("Shiny","ShinyShinyCPriceSummary").setValue("Add Shininess");
        getNode().getNode("Shiny","ShinyShinyShinyFalse").setValue("§8§lNon-Shiny");
        getNode().getNode("Shiny","ShinyShinyShinyFalseChoose").setValue("Click here to select the §8Non-Shiny §7option.");
        getNode().getNode("Shiny","ShinyShinyShinyTrue").setValue("§6§lShiny");
        getNode().getNode("Shiny","ShinyShinyShinyTrueChoose").setValue("Click here to select the §6Shiny §7option.");
        getNode().getNode("Shiny","ShinyShinyTitle").setValue("Shininess Modification");
        getNode().getNode("Shop","ShopABILITY").setValue("Ability");
        getNode().getNode("Shop","ShopBackToMenu").setValue("Back to menu");
        getNode().getNode("Shop","ShopBuy").setValue("Purchasing");
        getNode().getNode("Shop","ShopCancel").setValue("Cancel");
        getNode().getNode("Shop","ShopCheckoutAsk").setValue("This will take you to the final checkout page.");
        getNode().getNode("Shop","ShopCheckoutTitle").setValue("Checkout");
        getNode().getNode("Shop","ShopChoosedPokemon").setValue("Selected Pokemon");
        getNode().getNode("Shop","ShopConfirm").setValue("Confirm");
        getNode().getNode("Shop","ShopConfirmDONE").setValue("Successfully edited your Pokemon!");
        getNode().getNode("Shop","ShopConfirmInfo1").setValue("Your total cost is: §c");
        getNode().getNode("Shop","ShopConfirmInfo2").setValue("Clicking this button will confirm your purchase.");
        getNode().getNode("Shop","ShopConfirmInfo3").setValue("Once clicked, changes cannot be reversed.");
        getNode().getNode("Shop","ShopConfirmInfo4").setValue("Your updated balance will be §a");
        getNode().getNode("Shop","ShopConfirmInfoError").setValue("You are not able to make this transaction");
        getNode().getNode("Shop","ShopConfirmInfoLackOfMoney").setValue("You are not able to make this purchase.");
        getNode().getNode("Shop","ShopCurrBalance").setValue("§2Current Balance: §a");
        getNode().getNode("Shop","ShopCurrentChoose").setValue("Current choose: §e");
        getNode().getNode("Shop","ShopCurrentCost").setValue("Current Cost:");
        getNode().getNode("Shop","ShopEditAskPart1").setValue("Click here if you wish to modify your Pokemon's ");
        getNode().getNode("Shop","ShopEditAskPart2").setValue(".");
        getNode().getNode("Shop","ShopEVOLUTION").setValue("Evolution");
        getNode().getNode("Shop","ShopFORM").setValue("Form");
        getNode().getNode("Shop","ShopGENDER").setValue("Gender");
        getNode().getNode("Shop","ShopGROWTH").setValue("Growth");
        getNode().getNode("Shop","ShopInfo").setValue("Info");
        getNode().getNode("Shop","ShopIVEV").setValue("IVs/EVs");
        getNode().getNode("Shop","ShopLEVEL").setValue("Level");
        getNode().getNode("Shop","ShopMOVE").setValue("Moves");
        getNode().getNode("Shop","ShopNATURE").setValue("Nature");
        getNode().getNode("Shop","ShopNICK").setValue("Nick");
        getNode().getNode("Shop","ShopPOKEBALL").setValue("Pokeball");
        getNode().getNode("Shop","ShopPressRefresh").setValue("[click to refresh]");
        getNode().getNode("Shop","ShopPrice").setValue("Prices:");
        getNode().getNode("Shop","ShopReset").setValue("Reset options");
        getNode().getNode("Shop","ShopSHINY").setValue("Shiny");

        getNode().getNode("Zen","ZenUnknown").setValue("Unknown");
        getNode().getNode("Zen","ZenEmpty").setValue("Empty");
        getNode().getNode("Zen","ZenCMDErrorPlayer").setValue("This command can only be executed by a player");
        getNode().getNode("Zen","ZenPokeDesign").setValue("pokeselector");
        getNode().getNode("Zen","ZenCMDPokeCant").setValue("That Pokemon cant use the PokeDesigner!");
        getNode().getNode("Zen","ZenArcDesign").setValue("Arceus Selector");
        getNode().getNode("Zen","ZenCMDArcOnly").setValue("Please only select an Arceus!");
        getNode().getNode("Zen","ZenSpongeError1").setValue("That Plate is already equipped!");
        getNode().getNode("Zen","ZenSpongeError2").setValue("Cant unequip ");
        getNode().getNode("Zen","ZenSpongeError3").setValue(" Plate because there is another in Storage! Please remove the one in Storage first before unequiping.");
        getNode().getNode("Zen","ZenSpongeEquip").setValue("Plate equipped!");
        getNode().getNode("Zen","ZenSpongeError4").setValue("Cannot equip Plate because Pokemon is currently holding something!");
        getNode().getNode("Zen","ZenSpongeErro5").setValue("Your inventory is full!");
        getNode().getNode("Zen","ZenPokeModiError1").setValue("This command can only be executed by a player unless one is specified");
        getNode().getNode("Zen","ZenPokeModiPart1").setValue("Given ");
        getNode().getNode("Zen","ZenPokeModiPart2").setValue(" modifier!");
        getNode().getNode("Zen","ZenPokeModiError2").setValue("That modifier doesn't exist");
        getNode().getNode("Zen","ZenPokeShrineError1").setValue("This shrine is locked for pickup by another player");
        getNode().getNode("Zen","ZenPokeShrineError2").setValue("Clicking the placed shrine with an empty hand will lock it to stop other players from picking it up");
        getNode().getNode("Zen","ZenPokeShrineError3").setValue("Your inventory is full!");
        getNode().getNode("Zen","ZenPokeShrineError4").setValue("This shrine has been unlocked for pickup");
        getNode().getNode("Zen","ZenPokeShrineError5").setValue("This shrine is already locked for pickup by another player");
        getNode().getNode("Zen","ZenPokeShrineError6").setValue("This shrine has been locked for pickup");
        getNode().getNode("Zen","ZenWrapperLEVEL").setValue("§r §7: §eLevel ");
        getNode().getNode("Zen","ZenWrapperSHINY").setValue(" §7(§6✯Shiny✯§7)");
        getNode().getNode("Zen","ZenWrapperABILITY").setValue("§7Ability: §e");
        getNode().getNode("Zen","ZenWrapperNATURE").setValue("§7Nature: §e");
        getNode().getNode("Zen","ZenWrapperNoSex").setValue("§eNon");
        getNode().getNode("Zen","ZenWrapperMale").setValue("§bMale");
        getNode().getNode("Zen","ZenWrapperFemale").setValue("§dFemale");
        getNode().getNode("Zen","ZenWrapperGENDER").setValue("§7Gender:");
        getNode().getNode("Zen","ZenWrapperGROWTH").setValue("§7Growth: §e");
        getNode().getNode("Zen","ZenWrapperEVOLUTION").setValue("§7Evolution: §e");
        getNode().getNode("Zen","ZenWrapperPOKEBALL").setValue("§7Pokeball: §e");
        getNode().getNode("Zen","ZenWrapperFORM").setValue("§7Form: §e");
        getNode().getNode("Zen","ZenWrapperPokeurs").setValue("§dPokeurs");
        getNode().getNode("Zen","ZenWrapperStats").setValue("§8(§cHP§8/§cATK§8/§cDEF§8/§cSA§8/§cSD§8/§cSPD§8)");


        super.configUpdater(newVersion);
    }

    public abstract URL getUrl();
}
